### ISSUE TITLE
[1.16] [Mod-Incompat] Custom Player Models - Server crash.

### ISSUE THREAD

**Issue by Cixon** [noobanidus/toofast#1]
Ported from CPM's github.

https://github.com/tom5454/CustomPlayerModels/issues/159

**Comment by noobanidus** [comment]
As noted on the project page:

> Conflicts with Random Patches. Do not bother installing this if you've installed Random Patches.

You have Random Patches installed. There's nothing wrong with the refmap. Just uninstall Too Fast -- Random Patches already performs this functionality.
