### ISSUE TITLE
Couldn't load - Jar does not contain plugin.yml

### ISSUE THREAD

**Issue by jcw19k** [noobanidus/toofast#2]
Getting an error here, can't load the plugin as it does not contain a plugin.yml file

**Comment by noobanidus** [comment]
Hi there!

This is a Forge mod, so you will need to have Forge installed to run it. As far as I'm aware, `plugin.yml` is specifically used for Spigot plug-ins.

**Comment by jcw19k** [comment]
Whoops, that's what I get for downloading plugins without looking, thanks :)
