### ISSUE TITLE
1.19.2 working

### ISSUE THREAD

**Issue by gamerpotion** [noobanidus/toofast#6]
Hi, I was using the current 1.19 release on our modpack which is 1.19.2 - https://www.curseforge.com/minecraft/modpacks/darkrpg

I havent noticed any errors in console, does that mean the mod is working fine or does it need updating?

If the 1.19 version is working fine, are you able to tick the 1.19.2 checkbox in the files section so it can officially be added to modpack 

thanks

**Comment by hacheraw** [comment]
I'm on 1.19.2
Installed it. No errors on console BUT still "moved too quick!"

![image](https://user-images.githubusercontent.com/10481749/211939920-2bd4da02-7d3c-4564-8fab-cc070ebf2445.png)

**Comment by MarioSMB** [comment]
+1 to this, please mark 1.19.2 as compatible so users of the CurseForge client can install the mod, thanks!

**Comment by noobanidus** [comment]
@MarioSMB Unfortunately there were some changes in 1.19.2 etc that make this mod non-functional. While it is technically compatible with 1.19.2, it doesn't actually remove all of the issues or the rubberbanding. I'll be trying to work on that later this month.

**Comment by LiskoSlayer63** [comment]
@noobanidus Any news yet?

**Comment by noobanidus** [comment]
@LiskoSlayer63 I've done a Forge release for 1.19 which seems to function as far as I can tell. Going to look into 1.19.3 for both Forge and Fabric as I believe they still have issues.

**Comment by LiskoSlayer63** [comment]
@noobanidus Thank you for your hard work, installed to the server now :)

**Comment by Yourname942** [comment]
> 

Does this mean you are skipping over 1.19.2? :(

**Comment by noobanidus** [comment]
@Yourname942 The version released should be compatible with 1.19.2.

**Comment by Yourname942** [comment]
> 

The 1.19.3 version?

**Comment by noobanidus** [comment]
@Yourname942 The 1.19.0 version is for 1.19.0, 1.19.1, and 1.19.2.
